dist: focal
language: python
python:
- '3.8'
env:
  jobs:
  - TOX_ENV=tanguan
  - TOX_ENV=bunpun
  - TOX_ENV=HTS
  - TOX_ENV=HTK
  - TOX_ENV=KenLM
#  - TOX_ENV=Moses
  - TOX_ENV=ckip
  - TOX_ENV=naer
  - TOX_ENV=flake8
services:
- docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - python3-dev
    - libc6-dev-i386
    - linux-libc-dev
    - gcc-multilib
    - git
    - subversion
    - automake
    - libtool
    - zlib1g-dev
    - libbz2-dev
    - liblzma-dev
    - libboost-all-dev
    - libgoogle-perftools-dev
    - libxmlrpc-c++.*-dev
    - cmake
    - csh
install:
- sudo apt-get update
- sudo apt-get install libx11-dev
- pip install tox
- pip install python-coveralls
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
  - siu-ghpage
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        username: sih4sing5hong5
        password:
          secure: QRLD6yPZ92b//ylVExoFZO+BGlHGZ/6ktu8nYIcnZTdE3zJsHR5fAlEkvELpT1yCHr//LU4ovcZ5O/R28YY/+naj/8cRqv4K5yvV70Wq5Sbj+TtQBuaNkMb3Vnif7GlLro9PZK2l224mBJsqFvykg9OLm+TBcRUB0fJMeS4x4gMQiOvWWDPyWAq/toJ6qknQqO199r8sbwu5BJtC0wo6nly048a46RcpTb9bkOil/i6gcA/X8TNDMmc1ah7XHp1zBwnUA6TQ0BfBu+COanwLykIG1Q8CsCp2+bH7CdPDZDZk0qTKlMSZFT5wWD0a3ABnPbXKcynUeCORgKpIW2JrHzTbQT4RW1OfDJ4LKXK+IS9H6qEgECkPPXcbySYDJabpz0bAy6JkkMB9q8PuHTII8vluwwgKT3Ws2LyqseE/tY6lZbF+dQRylEfzCGYOV+ICWYHsA3Nx2tDaxmHJFTKpLkK8yTxpJd0o6NJffIsIFIBEMQehXPyBELRxkJ1OMVMK3wE5u5nb7hlMoOpzG4KgxhBQi79/Iz1V9scC2Jp1vrwFJF/zNZIID1aMWHYBWBkytfjo9GnaUV3jADPbXhCy+K6Igbn8QRVjRXhxDEow844KvPxQ7NzCU1JDP2nNup1+NKNcWCAExs5wSw0wYTyYxizi6BXhepvYeWzV4gMzAZQ=
        on:
          tags: true
    - script: skip
      before_deploy:
      - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        local_dir: "文件/_build/html"
        on:
          branch: siu-ghpage
