dist: jammy
language: python
python:
- '3.8'
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
jobs:
  include:
    - name: tanguan
      addons:
        sonarcloud:
          organization: "ithuan"
          token: ${SONAR_TOKEN}
      install:
        - pip install tox
      script:
        - tox -e tanguan
      after_success:
        - sonar-scanner
    - name: bunpun
      addons:
        sonarcloud:
          organization: "ithuan"
          token: ${SONAR_TOKEN}
      install:
        - pip install tox
      script:
        - tox -e bunpun
      after_success:
        - sonar-scanner
    - name: HTS
      addons:
        sonarcloud:
          organization: "ithuan"
          token: ${SONAR_TOKEN}
      install:
        - pip install tox
      script:
        - tox -e HTS
      after_success:
        - sonar-scanner
    - name: KenLM
      install:
        - pip install tox
      script:
        - tox -e KenLM
    - name: flake8
      install:
        - pip install tox
      script:
        - tox -e flake8
    - stage: sonarcloud
      name: coverage
      addons:
        sonarcloud:
          organization: "ithuan"
          token: ${SONAR_TOKEN}
      install:
        - pip install tox
      script:
        - tox -e coverage
        - sonar-scanner
    - stage: deploy
      name: pypi
      if: branch ~= /\d+\.\d+\.\d+/
      script: skip
      deploy:
        provider: pypi
        username: __token__
        password: ${PYPI_PASSWORD}
        on:
          tags: true
    - name: gh-page bunkiann
      if: type == push AND branch == master
      install:
        - pip install tox
      script:
       - tox -e bunkiann
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        local_dir: "html"
        on:
          branch: master
