dist: focal
language: python
python:
- '3.8'
env:
  jobs:
  - TOX_ENV=tanguan
  - TOX_ENV=bunpun
  - TOX_ENV=HTS
  - TOX_ENV=HTK
  - TOX_ENV=KenLM
#  - TOX_ENV=Moses
  - TOX_ENV=ckip
  - TOX_ENV=naer
  - TOX_ENV=flake8
services:
- docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - python3-dev
    - libc6-dev-i386
    - linux-libc-dev
    - gcc-multilib
    - git
    - subversion
    - automake
    - libtool
    - zlib1g-dev
    - libbz2-dev
    - liblzma-dev
    - libboost-all-dev
    - libgoogle-perftools-dev
    - libxmlrpc-c++.*-dev
    - cmake
    - csh
install:
- sudo apt-get update
- sudo apt-get install libx11-dev
- pip install tox
- pip install python-coveralls
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
  - siu-ghpage
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls

jobs:
  include:
    - stage: deploy
      name: pypi
      if: branch ~= /\d+\.\d+\.\d+/
      script: skip
      deploy:
        provider: pypi
        username: __token__
        password: ${PYPI_PASSWORD}
        on:
          tags: true
    - name: gh-page bunkiann
      script:
      - tox -e bunkiann
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        local_dir: "文件/_build/html"
        on:
          branch: siu-ghpage
