dist: focal
language: python
python:
- '3.8'
env:
  jobs:
  - TOX_ENV=tanguan
  - TOX_ENV=bunpun
  - TOX_ENV=HTS
  - TOX_ENV=KenLM
  - TOX_ENV=flake8
services:
- docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - python3-dev
install:
- pip install tox
- pip install python-coveralls
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls

jobs:
  include:
    - stage: deploy
      name: pypi
      if: branch ~= /\d+\.\d+\.\d+/
      script: skip
      deploy:
        provider: pypi
        username: __token__
        password: ${PYPI_PASSWORD}
        on:
          tags: true
    - name: gh-page bunkiann
      if: type == push AND branch == master
      script:
      - tox -e bunkiann
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        local_dir: "html"
        on:
          branch: master
