dist: jammy
language: python
python:
- '3.8'
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
jobs:
  include:
    - name: tanguan
      install:
        - pip install tox
      script:
        - tox -e tanguan
      after_success:
        - pip install awscli
        - aws s3 cp coverage.xml s3://${AWS_S3_BUCKET}/${TRAVIS_BUILD_NUMBER}/coverage-tanguan.xml
    - name: bunpun
      install:
        - pip install tox
      script:
        - tox -e bunpun
      after_success:
        - pip install awscli
        - aws s3 cp coverage.xml s3://${AWS_S3_BUCKET}/${TRAVIS_BUILD_NUMBER}/coverage-bunpun.xml
    - name: HTS
      install:
        - pip install tox
      script:
        - tox -e HTS
      after_success:
        - pip install awscli
        - aws s3 cp coverage.xml s3://${AWS_S3_BUCKET}/${TRAVIS_BUILD_NUMBER}/coverage-HTS.xml
    - name: KenLM
      install:
        - pip install tox
      script:
        - tox -e KenLM
      after_success:
        - pip install awscli
        - aws s3 cp coverage.xml s3://${AWS_S3_BUCKET}/${TRAVIS_BUILD_NUMBER}/coverage-KenLM.xml
    - name: flake8
      install:
        - pip install tox
      script:
        - tox -e flake8
    - stage: sonarcloud
      addons:
        sonarcloud:
          organization: "ithuan"
          token: ${SONAR_TOKEN}
      name: coverage
      install: skip
      before_script:
        - pip install awscli
        - aws s3 sync s3://${AWS_S3_BUCKET}/${TRAVIS_BUILD_NUMBER}/ .coverage-reports/
      script:
        - sonar-scanner
    - stage: deploy
      name: pypi
      if: branch ~= /\d+\.\d+\.\d+/
      script: skip
      deploy:
        provider: pypi
        username: __token__
        password: ${PYPI_PASSWORD}
        on:
          tags: true
    - name: gh-page bunkiann
      if: type == push AND branch == master
      install:
        - pip install tox
      script:
       - tox -e bunkiann
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        local_dir: "html"
        on:
          branch: master
